### ISSUE TITLE
unsafeSVG makes hydration fail

### ISSUE THREAD

**Issue by ingvilddev** [popeindustries/lit#28]
Had some trouble making a page hydrate correctly.
Got the error message:
```
Error: unexpected TemplateResult rendered to part
    at openChildPart (index.js:259:13)
    at render (index.js:125:28)
    at SearchPageElement.requestRender (base-element.ts:8:7)
    at SearchPageElement.updated (search-page.ts:80:10)
    at SearchPageElement._invalidate (reactive-element.js:746:12)

hydration failed. Clearing nodes and performing clean render
```

Think we managed to scope it down to the `unsageSVG` directive being the problem, since when the small svg icon using this directive was removed, hydration was successful.

### From server:
```html
<!--lit ej7laDxdFzw=-->
<search-page
  class="display-block margin-x-page-s color-white"
  hydrate:defer
  ><!--lit-attr 3--><!--lit BRUAAAUVAAA=--><!--lit-child-->some svg text<!--/lit-child--><!--/lit-->
</search-page>
<!--/lit-->
```

### Rendered by client:
```html
<!--lit ej7laDxdFzw=-->
<search-page class="display-block margin-x-page-s color-white"
  ><!--lit-attr 3--><!----><!--?lit$37119816$-->some svg text<!--?-->
</search-page>
<!--/lit-->
```

**Comment by popeindustries** [comment]
Can you show me the template as well? `unsafeSVG` should only be used on the _inside_ of an `<svg></svg>` tag. If you need to embed an svg string that contains it's own opening/closing tag, `unsafeHTML` is the correct directive to use in that case:

```js
const svgContent = '<path
      fill="currentColor"
      fill-rule="evenodd"
      clip-rule="evenodd"
      d="M10 19...."
    />';

html`<div><svg>${unsafeSVG(svgContent)}</svg></div>`;
html`<div>${unsafeHTML(`<svg>${svgContent}</svg>`)}</div>`;
```

**Comment by popeindustries** [comment]
Actually, this is a bug! We need to treat directives like `TemplateResults`, with a hash

**Comment by ingvilddev** [comment]
@popeindustries Was wondering if also this was a related bug, but I am unsure, maybe I am just writing bad code. 
But, I get the error: 
```
Uncaught (in promise) DOMException: Failed to execute 'remove' on 'DOMTokenList': The token provided 
('animation-fade-in-and-pulse position-relative width-fit-content stencil') contains HTML space characters, 
which are not valid in tokens.
    at ClassMapDirective.update (http://localhost:8080/Users/n646887/nrktv/nrk-tv-web/apps/web/node_modules/
.pnpm/@popeindustries+lit-html@5.1.0/node_modules/
@popeindustries/lit-html/src/vendor/directives/class-map.js:67:31)
etc...
```

This bug surfaces when we use `classMap()` like this:
```html
<button
          class="tv-button display-block text-style-body margin-x-auto margin-bottom-m ${classMap(
            {
              'animation-fade-in-and-pulse position-relative width-fit-content stencil':
                isLoading,
            }
          )}"
        >
```

but it is alright when it is used like this:
```html
html`<button
          class="tv-button display-block text-style-body margin-x-auto margin-bottom-m ${classMap(
            {
              'animation-fade-in-and-pulse position-relative': isLoading,
              'position-relative': isLoading,
              'width-fit-content': isLoading,
              'animation-stencil': isLoading,
            }
          )}"
        >
```

Reading from the documentation [here](https://lit.dev/docs/templates/directives/#classmap) that it absolutely looks like it's intended use is to toggle on/off single classes (thus no spaces).
But what bothers me is that is seemingly works ok other places when the code only runs on the client, but _not_ when the same lines of code _also_ runs on the server? 
Sorry if this comment includes too little information, just wanted to know if you immediately realised something similar, that also the classMap() directive needs  specific handling, seeing that the fix in https://github.com/popeindustries/lit/pull/29/files#diff-7250f539eb39c11ad96e5c323257ab93acb94e4af28e7030d9231a75703c47acR542 only targets the `unsafeHTML` and `unsafeSVG` directives specifically 🙂 😅

**Comment by popeindustries** [comment]
I think this is unrelated to the fix here, but still interesting. I guess there is different handling internally when hydrating vs rendering-only that lit isn't accounting for because it's not the intended use case. 

The unsafe-* directives are special-cases here because they return "fake" `TemplateResult`s that need to be converted manually. All the other directives should just work.
